// Cuisine
 const cuisine = [
    "Réfrigérateur",
    "Congélateur",
    "Cuisinière",
    "Four",
    "Micro-ondes",
    "Lave-vaisselle",
    "Évier",
    "Hotte aspirante",
    "Bouilloire",
    "Grille-pain",
    "Machine à café",
    "Mixeur",
    "Batterie de cuisine",
    "Poêles",
    "Casseroles",
    "Plat à four",
    "Ustensiles de cuisine",
    "Planche à découper",
    "Couteaux de cuisine",
    "Verres",
    "Tasses",
    "Assiettes",
    "Bols",
    "Couverts",
    "Tiroirs de rangement",
    "Placards",
    "Tupperwares",
    "Plateau",
    "Set de table",
    "Serviettes de table",
    "Torchons",
    "Gants de cuisine",
    "Épluche-légumes",
    "Ciseaux de cuisine",
    "Ouvre-boîte",
    "Tire-bouchon",
    "Moulin à poivre",
    "Saladier",
    "Passoire",
    "Bouilloire électrique",
    "Épices",
    "Poubelle de cuisine",
    "Sachets de conservation",
    "Film alimentaire",
    "Papier aluminium",
    "Papier cuisson",
    "Tapis de cuisson en silicone",
    "Louches",
    "Minuteur de cuisine",
  ];

  const kitchen = [
    "Refrigerator",
    "Freezer",
    "Stove",
    "Oven",
    "Microwave",
    "Dishwasher",
    "Sink",
    "Range hood",
    "Kettle",
    "Toaster",
    "Coffee maker",
    "Blender",
    "Cookware",
    "Frying pans",
    "Pots",
    "Baking dish",
    "Kitchen utensils",
    "Cutting board",
    "Kitchen knives",
    "Glasses",
    "Cups",
    "Plates",
    "Bowls",
    "Cutlery",
    "Storage drawers",
    "Cupboards",
    "Tupperware",
    "Tray",
    "Placemat",
    "Napkins",
    "Dish towels",
    "Oven mitts",
    "Vegetable peeler",
    "Kitchen scissors",
    "Can opener",
    "Corkscrew",
    "Pepper mill",
    "Salad bowl",
    "Strainer",
    "Electric kettle",
    "Spices",
    "Kitchen trash can",
    "Storage bags",
    "Cling film",
    "Aluminum foil",
    "Parchment paper",
    "Silicone baking mat",
    "Ladles",
    "Kitchen timer",
  ];
  


module.exports = cuisine;

// Salle à manger
const salleAManger = [
  "Table à manger",
  "Chaises",
  "Nappe",
  "Serviettes de table",
  "Chemin de table",
  "Set de table",
  "Vaisselle de présentation",
  "Carafe d’eau",
  "Pichet",
  "Verres à vin",
  "Verres à eau",
  "Assiettes à dessert",
  "Plats de service",
  "Étagère à vin",
  "Centre de table",
  "Chauffe-plat",
  "Buffet",
  "Argenterie",
  "Étagère de rangement",
  "Table extensible",
  "Luminaire suspendu",
  "Tableau mural",
  "Plante en pot",
  "Chandeliers",
  "Bougies",
  "Portes-assiettes",
  "Couverts en argent",
  "Serviteur muet",
  "Panier à pain",
  "Saladier",
  "Plateau de service",
  "Support pour bouteilles",
  "Tire-bouchon électrique",
  "Paniers à fruits",
  "Vase",
  "Miroir mural",
  "Assiettes creuses",
  "Corbeille à pain",
  "Seau à champagne",
  "Verres à cocktails",
  "Sous-verres",
  "Serviteur à trois niveaux",
  "Pots pour épices",
  "Huilier",
  "Pichet à lait",
  "Salière et poivrière",
  "Porte-serviettes",
  "Photophores",
  "Présentoir à gâteaux",
  "Ménagère"
];

const diningRoom = [
  "Dining table",
  "Chairs",
  "Tablecloth",
  "Napkins",
  "Table runner",
  "Placemat",
  "Serving dishes",
  "Water carafe",
  "Pitcher",
  "Wine glasses",
  "Water glasses",
  "Dessert plates",
  "Serving platters",
  "Wine rack",
  "Centerpiece",
  "Food warmer",
  "Buffet",
  "Silverware",
  "Storage shelf",
  "Extendable table",
  "Pendant light",
  "Wall art",
  "Potted plant",
  "Candlesticks",
  "Candles",
  "Plate holders",
  "Silver cutlery",
  "Lazy Susan",
  "Bread basket",
  "Salad bowl",
  "Serving tray",
  "Bottle holder",
  "Electric corkscrew",
  "Fruit baskets",
  "Vase",
  "Wall mirror",
  "Soup plates",
  "Bread basket",
  "Champagne bucket",
  "Cocktail glasses",
  "Coasters",
  "Three-tiered stand",
  "Spice jars",
  "Oil bottle",
  "Milk pitcher",
  "Salt and pepper shakers",
  "Napkin holder",
  "Tealight holders",
  "Cake stand",
  "Cutlery set",
];

// L'entrée
const entree = [
  "Porte-manteaux",
  "Paillasson",
  "Meuble à chaussures",
  "Porte-parapluies",
  "Portant",
  "Miroir mural",
  "Console",
  "Table d’entrée",
  "Tapis",
  "Porte-clefs",
  "Armoire d’entrée",
  "Coffre de rangement",
  "Patère",
  "Banc d’entrée",
  "Vide-poches",
  "Porte-lettres",
  "Étagère murale",
  "Éclairage d’entrée",
  "Porte-chapeaux",
  "Portail",
  "Sonnette",
  "Caméra de surveillance",
  "Interphone",
  "Bac à recyclage",
  "Détecteur de mouvement",
  "Système d’alarme",
  "Porte-nom",
  "Boîte à clés",
  "Numéro de maison",
  "Cloche",
  "Fleurs fraîches",
  "Parfum d’intérieur",
  "Cendrier",
  "Étagère à parapluie",
  "Boîte à chaussures",
  "Miroir avec rangement",
  "Parasol mural",
  "Espace de rangement supplémentaire",
  "Support mural pour vélos",
  "Porte-chien",
  "Chaise d’entrée",
  "Étagère à casques",
  "Rangement pour accessoires",
  "Plante d’intérieur",
  "Clavier à code",
  "Cadre photo",
  "Étagère à chapeaux",
  "Porte-revues",
  "Porte-écharpe",
  "Horloge"
];

const entryway = [
  "Coat rack",
  "Doormat",
  "Shoe cabinet",
  "Umbrella stand",
  "Clothes rack",
  "Wall mirror",
  "Console table",
  "Entry table",
  "Rug",
  "Key holder",
  "Entryway closet",
  "Storage chest",
  "Hook",
  "Entryway bench",
  "Catch-all tray",
  "Letter holder",
  "Wall shelf",
  "Entry lighting",
  "Hat rack",
  "Gate",
  "Doorbell",
  "Security camera",
  "Intercom",
  "Recycling bin",
  "Motion detector",
  "Alarm system",
  "Nameplate",
  "Key box",
  "House number",
  "Bell",
  "Fresh flowers",
  "Home fragrance",
  "Ashtray",
  "Umbrella shelf",
  "Shoe box",
  "Mirror with storage",
  "Wall-mounted umbrella",
  "Extra storage space",
  "Wall-mounted bike rack",
  "Dog gate",
  "Entry chair",
  "Helmet rack",
  "Accessory storage",
  "Indoor plant",
  "Keypad",
  "Photo frame",
  "Hat shelf",
  "Magazine holder",
  "Scarf holder",
  "Clock"
];


// terrasse
const terrasse = [
  "Parasol",
  "Table d’extérieur",
  "Chaises d’extérieur",
  "Chaise longue",
  "Tapis d’extérieur",
  "Balancelle",
  "Barbecue",
  "Plantes en pot",
  "Coussins d’extérieur",
  "Pergola",
  "Éclairage extérieur",
  "Brise-vue",
  "Chauffage de terrasse",
  "Guirlandes lumineuses",
  "Étagères d’extérieur",
  "Fontaine",
  "Paillasson extérieur",
  "Panier de rangement",
  "Housse de protection",
  "Paravent",
  "Potager",
  "Grillages de protection",
  "Banc d’extérieur",
  "Bain de soleil",
  "Hamac",
  "Voile d’ombrage",
  "Tente de jardin",
  "Bar d’extérieur",
  "Chauffe-eau extérieur",
  "Plancha",
  "Jeu de quilles",
  "Parasol chauffant",
  "Corbeille à fleurs",
  "Supports pour parasol",
  "Boîte de rangement étanche",
  "Serre de balcon",
  "Étagère à plantes",
  "Balustrades",
  "Grillage",
  "Cendrier extérieur",
  "Distributeur d’eau",
  "Plateau de service",
  "Glacière",
  "Banc de jardin",
  "Abri de jardin",
  "Brumisateur",
  "Table basse d’extérieur",
  "Jeu de société d’extérieur",
  "Lanterne",
  "Radiateur extérieur"
];

const terrace = [
  "Parasol",
  "Outdoor table",
  "Outdoor chairs",
  "Lounge chair",
  "Outdoor rug",
  "Swing chair",
  "Barbecue",
  "Potted plants",
  "Outdoor cushions",
  "Pergola",
  "Outdoor lighting",
  "Privacy screen",
  "Patio heater",
  "String lights",
  "Outdoor shelves",
  "Fountain",
  "Outdoor doormat",
  "Storage basket",
  "Protective cover",
  "Screen",
  "Vegetable garden",
  "Protective fencing",
  "Outdoor bench",
  "Sunbed",
  "Hammock",
  "Shade sail",
  "Garden tent",
  "Outdoor bar",
  "Outdoor water heater",
  "Grill",
  "Quoits game",
  "Heated parasol",
  "Flower basket",
  "Umbrella stand",
  "Waterproof storage box",
  "Balcony greenhouse",
  "Plant shelf",
  "Railings",
  "Fencing",
  "Outdoor ashtray",
  "Water dispenser",
  "Serving tray",
  "Cooler",
  "Garden bench",
  "Garden shed",
  "Mister",
  "Outdoor coffee table",
  "Outdoor board game",
  "Lantern",
  "Outdoor radiator"
];


// garage
const garage = [
  "Porte de garage automatique",
  "Rangement pour outils",
  "Établi",
  "Perceuse",
  "Scie",
  "Marteau",
  "Clous",
  "Vis",
  "Tournevis",
  "Meuleuse",
  "Ponceuse",
  "Peinture",
  "Pinceaux",
  "Échelle",
  "Etau",
  "Compresseur",
  "Cric",
  "Clé à molette",
  "Poste à souder",
  "Tondeuse",
  "Râteau",
  "Pelle",
  "Brouette",
  "Espace de rangement",
  "Coffre à outils",
  "Pince multiprise",
  "Clé dynamométrique",
  "Huiles de moteur",
  "Batterie de voiture",
  "Pompe à vélo",
  "Gonfleur de pneus",
  "Caisse à outils",
  "Support pour vélos",
  "Poubelle de garage",
  "Support pour pneus",
  "Rangement mural",
  "Tapis de sol",
  "Chaise de mécanicien",
  "Aspirateur de garage",
  "Éclairage LED",
  "Chargeur de batterie",
  "Détecteur de fumée",
  "Armoire à produits chimiques",
  "Boîte de rangement pour pièces",
  "Sac de rangement",
  "Chauffage de garage",
  "Ventilateur de garage",
  "Porte-clés magnétique",
  "Rangement pour câbles",
  "Boîte à outils portable"
];

const garage_ = [
  "Automatic garage door",
  "Tool storage",
  "Workbench",
  "Drill",
  "Saw",
  "Hammer",
  "Nails",
  "Screws",
  "Screwdriver",
  "Grinder",
  "Sander",
  "Paint",
  "Paintbrushes",
  "Ladder",
  "Vise",
  "Compressor",
  "Jack",
  "Wrench",
  "Welding station",
  "Lawnmower",
  "Rake",
  "Shovel",
  "Wheelbarrow",
  "Storage area",
  "Toolbox",
  "Pliers",
  "Torque wrench",
  "Engine oils",
  "Car battery",
  "Bicycle pump",
  "Tire inflator",
  "Tool chest",
  "Bike rack",
  "Garage trash can",
  "Tire holder",
  "Wall storage",
  "Floor mat",
  "Mechanic's chair",
  "Garage vacuum",
  "LED lighting",
  "Battery charger",
  "Smoke detector",
  "Chemical cabinet",
  "Parts storage box",
  "Storage bag",
  "Garage heater",
  "Garage fan",
  "Magnetic key holder",
  "Cable storage",
  "Portable toolbox"
];


// piscine
const piscine = [
  "Skimmer",
  "Échelle de piscine",
  "Bâche de piscine",
  "Filtration",
  "Robot de piscine",
  "Chauffage de piscine",
  "Alarme de piscine",
  "Thermomètre de piscine",
  "Kit de traitement de l’eau",
  "Épuisette",
  "Chlore",
  "Kit de test de l’eau",
  "Tuyau d’arrosage",
  "Nettoyeur à pression",
  "Bouées",
  "Flotteurs",
  "Jeux aquatiques",
  "Planches de natation",
  "Bonnet de bain",
  "Maillot de bain",
  "Lunettes de natation",
  "Serviettes de plage",
  "Transats",
  "Parasol",
  "Fontaine de piscine",
  "Diffuseur de chlore",
  "Escalier de piscine",
  "Douche solaire",
  "Tapis de sol antidérapant",
  "Rideaux de piscine",
  "Éclairage submersible",
  "Bouées pour enfants",
  "Système de régulation du pH",
  "Équipement de plongée",
  "Bar flottant",
  "Gilets de sauvetage",
  "Jeu de basket aquatique",
  "Filet de volley aquatique",
  "Parasol de piscine",
  "Banc de piscine",
  "Panneaux solaires pour piscine",
  "Éclairage LED subaquatique",
  "Système de chauffage par pompe à chaleur",
  "Tapis de piscine pour enfants",
  "Déshumidificateur de piscine intérieure",
  "Nettoyeur de ligne d’eau",
  "Couverture thermique",
  "Table de pique-nique de piscine",
  "Réchauffeur électrique",
  "Échelle de sécurité"
];
//Traduction piscine
const pool = [
  "Skimmer",
  "Pool ladder",
  "Pool cover",
  "Filtration",
  "Pool robot",
  "Pool heating",
  "Pool alarm",
  "Pool thermometer",
  "Water treatment kit",
  "Pool net",
  "Chlorine",
  "Water testing kit",
  "Garden hose",
  "Pressure cleaner",
  "Buoys",
  "Floaters",
  "Water games",
  "Swim boards",
  "Swim cap",
  "Swimsuit",
  "Swim goggles",
  "Beach towels",
  "Lounge chairs",
  "Umbrella",
  "Pool fountain",
  "Chlorine dispenser",
  "Pool stairs",
  "Solar shower",
  "Non-slip floor mat",
  "Pool curtains",
  "Underwater lighting",
  "Kids' floaters",
  "pH regulation system",
  "Diving equipment",
  "Floating bar",
  "Life jackets",
  "Water basketball game",
  "Water volleyball net",
  "Pool umbrella",
  "Pool bench",
  "Pool solar panels",
  "Underwater LED lighting",
  "Heat pump heating system",
  "Kids' pool mat",
  "Indoor pool dehumidifier",
  "Water line cleaner",
  "Thermal cover",
  "Pool picnic table",
  "Electric heater",
  "Safety ladder"
];
// salle de bain (de luxe)
const salleDeBainDeLuxe = [
  "Baignoire à jets",
  "Douche à l’italienne",
  "Meuble lavabo",
  "Double vasque",
  "Miroir anti-buée",
  "Chauffe-serviettes",
  "Robinetterie haut de gamme",
  "Paroi de douche en verre",
  "Système audio intégré",
  "Éclairage LED encastré",
  "Tapis de bain",
  "Étagère de rangement",
  "Poubelle de salle de bain",
  "Échelle de rangement",
  "Paniers à linge",
  "Distributeur de savon automatique",
  "Porte-serviettes chauffant",
  "Abattant WC avec bidet",
  "Miroir de maquillage",
  "Plantes d’intérieur",
  "Rideau de douche design",
  "Pouf",
  "Étagères murales",
  "Accessoires de bain en bambou",
  "Penderie à serviettes",
  "Accessoires de bain en métal",
  "Panier à linge en osier",
  "Distributeur de papier toilette",
  "Douche pluie",
  "Chaise de bain",
  "Séchoir de bain",
  "Écran LCD",
  "Étagère à produits de beauté",
  "Miroir grossissant",
  "Balnéothérapie",
  "Porte-savon en pierre",
  "Set de peignoirs",
  "Housse de baignoire",
  "Colonne de douche",
  "Éclairage d’ambiance",
  "Tablette pour baignoire",
  "Cache-pipes",
  "Sèche-cheveux intégré",
  "Panier de rangement sous lavabo",
  "Distributeur de brosses à dents",
  "Plateau à bijoux",
  "Penderie à accessoires",
  "Bac à bain pour enfants",
  "Système de purification de l’air",
  "Étagère à serviettes en métal"
];
//Traduction salle de bain
const luxuryBathroom = [
  "Jet bathtub",
  "Walk-in shower",
  "Sink cabinet",
  "Double sink",
  "Anti-fog mirror",
  "Heated towel rail",
  "High-end faucets",
  "Glass shower screen",
  "Built-in audio system",
  "Recessed LED lighting",
  "Bath mat",
  "Storage shelf",
  "Bathroom trash can",
  "Storage ladder",
  "Laundry baskets",
  "Automatic soap dispenser",
  "Heated towel holder",
  "Toilet seat with bidet",
  "Makeup mirror",
  "Indoor plants",
  "Designer shower curtain",
  "Pouf",
  "Wall shelves",
  "Bamboo bath accessories",
  "Towel wardrobe",
  "Metal bath accessories",
  "Wicker laundry basket",
  "Toilet paper dispenser",
  "Rain shower",
  "Bath chair",
  "Bathroom dryer",
  "LCD screen",
  "Beauty product shelf",
  "Magnifying mirror",
  "Balneotherapy",
  "Stone soap dish",
  "Robe set",
  "Bathtub cover",
  "Shower column",
  "Mood lighting",
  "Bathtub tray",
  "Pipe cover",
  "Built-in hair dryer",
  "Under-sink storage basket",
  "Toothbrush dispenser",
  "Jewelry tray",
  "Accessory wardrobe",
  "Kids' bath tub",
  "Air purification system",
  "Metal towel shelf"
];


// bureau à domicile
const bureauADomicile = [
  "Bureau ergonomique",
  "Chaise de bureau ajustable",
  "Lampe de bureau avec USB",
  "Ordinateur",
  "Écran de moniteur",
  "Imprimante multifonction",
  "Scanner",
  "Étagères de rangement",
  "Caisson de bureau",
  "Organisateur de bureau",
  "Bloc-notes",
  "Stylos et fournitures",
  "Système audio de bureau",
  "Tablette graphique",
  "Casque audio",
  "Filtre à papier",
  "Téléphone de bureau",
  "Repose-pieds",
  "Éclairage LED",
  "Câbles de gestion",
  "Poubelle de bureau",
  "Tapis de souris ergonomique",
  "Tableau blanc",
  "Étagère à livres",
  "Support pour ordinateur portable",
  "Distributeur de stylos",
  "Tableau de liège",
  "Planificateur",
  "Agenda",
  "Support de documents",
  "Porte-clés",
  "Accessoires de rangement",
  "Séparateurs de tiroirs",
  "Trieur de documents",
  "Station de recharge pour gadgets",
  "Porte-manteaux",
  "Support pour téléphone",
  "Horloge de bureau",
  "Organisateur de câbles",
  "Lampe de lecture",
  "Étagère d’angle",
  "Paravents",
  "Décorations murales",
  "Rangement sous bureau",
  "Porte-documents",
  "Pot de crayons",
  "Panneau d’affichage",
  "Support pour livres",
  "Étagère pour équipements",
  "Porte-ordi avec rangement intégré"
];
//Traduction bureau à domicile

const homeOffice = [
  "Ergonomic desk",
  "Adjustable office chair",
  "Desk lamp with USB",
  "Computer",
  "Monitor screen",
  "Multifunction printer",
  "Scanner",
  "Storage shelves",
  "Desk drawer unit",
  "Desk organizer",
  "Notepad",
  "Pens and supplies",
  "Desk audio system",
  "Graphics tablet",
  "Headphones",
  "Paper filter",
  "Office phone",
  "Footrest",
  "LED lighting",
  "Cable management",
  "Office trash can",
  "Ergonomic mouse pad",
  "Whiteboard",
  "Bookshelf",
  "Laptop stand",
  "Pen dispenser",
  "Corkboard",
  "Planner",
  "Diary",
  "Document stand",
  "Key holder",
  "Storage accessories",
  "Drawer dividers",
  "Document sorter",
  "Gadget charging station",
  "Coat rack",
  "Phone stand",
  "Desk clock",
  "Cable organizer",
  "Reading lamp",
  "Corner shelf",
  "Room dividers",
  "Wall decorations",
  "Under-desk storage",
  "Document holder",
  "Pencil holder",
  "Notice board",
  "Book stand",
  "Equipment shelf",
  "Laptop stand with storage"
];

// salle de cinéma
const salleDeCinema = [
  "Amplificateur",
  "Récepteur AV",
  "Étagères pour équipements",
  "Console de jeux",
  "Éclairage LED pour scène",
  "Rideaux occultants",
  "Tapis de salle de cinéma",
  "Téléviseur haute définition",
  "Système de câblage",
  "Banquette modulable",
  "Table basse",
  "Support pour télécommande",
  "Panneaux acoustiques",
  "Écran de projection motorisé",
  "Support pour projecteur",
  "Système de climatisation",
  "Réglage du volume",
  "Poufs",
  "Housse de protection pour équipements",
  "Distributeur de boissons",
  "Bar de cinéma",
  "Étagères à DVD/Blu-ray",
  "Table d’appoint",
  "Rideau de scène",
  "Décorations murales de cinéma",
  "Climatiseur portable",
  "Écran tactile de commande",
  "Support de tablette",
  "Décorations de film",
  "Boîte à popcorn",
  "Support pour câbles",
  "Éclairage d’ambiance",
  "Support mural pour haut-parleurs",
  "Caméra de sécurité",
  "Système de contrôle à distance",
  "Rangement pour accessoires",
  "Meuble multimédia",
  "Écran de projection enroulable",
  "Support pour accessoires de film",
  "Lecteur de streaming",
  "Décodeur TV"
];
//Traduction salle de cinéma
const homeCinema = [
  "Amplifier",
  "AV receiver",
  "Equipment shelves",
  "Gaming console",
  "Stage LED lighting",
  "Blackout curtains",
  "Cinema room carpet",
  "High-definition television",
  "Wiring system",
  "Modular seating",
  "Coffee table",
  "Remote control holder",
  "Acoustic panels",
  "Motorized projection screen",
  "Projector mount",
  "Air conditioning system",
  "Volume control",
  "Bean bags",
  "Equipment protective cover",
  "Beverage dispenser",
  "Cinema bar",
  "DVD/Blu-ray shelves",
  "Side table",
  "Stage curtain",
  "Cinema wall decor",
  "Portable air conditioner",
  "Touchscreen control panel",
  "Tablet holder",
  "Movie decor",
  "Popcorn box",
  "Cable organizer",
  "Ambient lighting",
  "Wall-mounted speaker stands",
  "Security camera",
  "Remote control system",
  "Accessory storage",
  "Multimedia console",
  "Retractable projection screen",
  "Film accessory stand",
  "Streaming player",
  "TV decoder"
];

// salle de loisirs
const salleDeLoisirs = [
  "Table de billard",
  "Baby-foot",
  "Table de ping-pong",
  "Jeux de société",
  "Consoles de jeux",
  "Écran de projection",
  "Projecteur",
  "Chaise longue",
  "Tapis de jeu",
  "Éclairage d’ambiance",
  "Table de jeu",
  "Canapé",
  "Fauteuils confortables",
  "Hamac"
];
//Traduction salle de loisirs
const recreationRoom = [
  "Billiard table",
  "Foosball table",
  "Ping-pong table",
  "Board games",
  "Game consoles",
  "Projection screen",
  "Projector",
  "Lounge chair",
  "Play mat",
  "Ambient lighting",
  "Game table",
  "Sofa",
  "Comfortable armchairs",
  "Hammock"
];
