const salon = [
    "Canapé",
    "Fauteuil",
    "Table basse",
    "Télévision",
    "Télécommande",
    "Rideaux",
    "Stores",
    "Lampe de salon",
    "Table d'appoint",
    "Bibliothèque",
    "Tapis",
    "Coussins décoratifs",
    "Cadres photo",
    "Peintures murales",
    "Plantes d'intérieur",
    "Horloge murale",
    "Cheminée",
    "Étagère murale",
    "Porte-revues",
    "Lecteur DVD",
    "Console de jeux",
    "Système audio",
    "Caisson de basses",
    "Barre de son",
    "Téléphone fixe",
    "Console",
    "Vase",
    "Chauffage",
    "Ventilateur",
    "Parasol",
    "Stores vénitiens",
    "Panier décoratif",
    "Repose-pieds",
    "Miroir décoratif",
    "Coffre de rangement",
    "Télécommande universelle",
    "Décodeur TV",
    "Prise multiple",
    "Cendrier",
    "Bougies décoratives",
    "Porte-bijoux",
    "Tableau blanc magnétique",
    "Lumiére d'ambiance",
    "Rideau à perles",
    "Paillasson",
    "Porte-parapluies",
    "Plaid de canapé",
    "Porte-manteaux",
    "Chaise longue",
    "Tabouret de bar"
  ];
console.log(salon);
  const bureau = [
    "Bureau",
    "Chaise de bureau",
    "Étagère de bureau",
    "Lampe de bureau",
    "Ordinateur",
    "Imprimante",
    "Scanner",
    "Corbeille à papier",
    "Tapis de souris",
    "Stylo",
    "Bloc-notes",
    "Enveloppes",
    "Tampon encreur",
    "Trousse de stylos",
    "Agrafeuse",
    "Agrafes",
    "Trombones",
    "Calendrier",
    "Organisateur de bureau",
    "Rangement pour documents",
    "Classeur",
    "Corbeille à courrier",
    "Cache-pot",
    "Station de recharge",
    "Règle",
    "Calculatrice",
    "Tablette",
    "Haut-parleurs",
    "Casque audio",
    "Téléphone fixe",
    "Webcams",
    "Boîte d’archivage",
    "Étagère murale",
    "Support pour ordinateur portable",
    "Chaise ergonomique",
    "Support à stylo",
    "Range-câbles",
    "Tableau blanc",
    "Tableau de liège",
    "Organiseur hebdomadaire",
    "Perforatrice",
    "Pince-notes",
    "Tablette graphique",
    "Bloc de papier",
    "Portemanteau",
    "Miroir de bureau",
    "Poubelle de bureau",
    "Enregistreur vocal",
    "Sous-main",
    "Lampe à LED"
];

// Afficher le tableau dans la console
console.log(bureau);

const buanderie = [
    "Machine à laver",
    "Sèche-linge",
    "Panier à linge",
    "Étendoir à linge",
    "Fer à repasser",
    "Planche à repasser",
    "Cintres",
    "Table de pliage",
    "Paniers de tri",
    "Pince à linge",
    "Produits de lessive",
    "Assouplissant",
    "Détachant",
    "Bac à linge sale",
    "Séchoir mural",
    "Bac de lavage",
    "Support pour fer à repasser",
    "Support à balais",
    "Étagère murale",
    "Machine à coudre",
    "Panier de rangement",
    "Pochettes de rangement",
    "Sac à linge",
    "Lessive en poudre",
    "Lessive liquide",
    "Nettoyant pour fer",
    "Kit de couture",
    "Sacs à linge délicat",
    "Rangement pour chaussures",
    "Balai",
    "Balai serpillère",
    "Produits nettoyants",
    "Aspirateur",
    "Seau",
    "Chiffons de nettoyage",
    "Gants en caoutchouc",
    "Échelle pliante",
    "Ventilateur",
    "Purificateur d’air",
    "Détartrant",
    "Adoucisseur d’eau",
    "Kit de réparation",
    "Ventilateur d’extraction",
    "Sèche-chaussures",
    "Sèche-couvertures",
    "Porte-savon",
    "Corde à linge",
    "Pochettes sous vide",
    "Rangement pour produits ménagers",
    "Aérateur de buanderie"
];

// Afficher le tableau dans la console
console.log(buanderie);

const salleDeJeux = [
    "Table de billard",
    "Baby-foot",
    "Table de ping-pong",
    "Jeux de société",
    "Console de jeux",
    "Jeux vidéo",
    "Télévision",
    "Système audio",
    "Chaises confortables",
    "Tapis de jeu",
    "Étagères de rangement",
    "Fléchettes",
    "Éclairage d’ambiance",
    "Meuble TV",
    "Fauteuils de jeu",
    "Jeu d’échecs",
    "Tables basses",
    "Canapés",
    "Posters muraux",
    "Station de recharge",
    "Jeux de cartes",
    "Table de poker",
    "Tapis de sol",
    "Coussins de sol",
    "Bar à snack",
    "Mini-frigo",
    "Armoire à jeux",
    "Rideaux occultants",
    "Jeux de construction",
    "Kit de peinture",
    "Jeux de plein air",
    "Échelle",
    "Piscine à balles",
    "Sac de frappe",
    "Panier de basket",
    "Table de hockey",
    "Jeux de puzzle",
    "Coin lecture",
    "Jouets en peluche",
    "Poufs",
    "Tente de jeu",
    "Tapis de danse",
    "Instruments de musique",
    "Jeux d’arcade",
    "Vélo d’appartement",
    "Jeu de fléchettes électronique",
    "Station de musique",
    "Peluches géantes",
    "Station de recharge pour manettes",
    "Jeu de tir"
];

// Afficher le tableau dans la console
console.log(salleDeJeux);

const salleDeSport = [
    "Tapis de yoga",
    "Haltères",
    "Banc de musculation",
    "Vélo d’appartement",
    "Tapis roulant",
    "Corde à sauter",
    "Élastiques de résistance",
    "Rouleau de massage",
    "Miroirs muraux",
    "Ballon de gym",
    "Kettlebell",
    "Poids de cheville",
    "Barre de traction",
    "Machine elliptique",
    "Vélo elliptique",
    "Sac de frappe",
    "Gants de boxe",
    "Banc de step",
    "Rangement pour poids",
    "Station de musculation",
    "Abdominaux Wheel",
    "Barre de musculation",
    "Machine à ramer",
    "Plancher de gym",
    "Barre de dips",
    "Station de crossfit",
    "Rack de squat",
    "Support pour haltères",
    "Échelle d’agilité",
    "Anneaux de gym",
    "Box jump",
    "Bouteille d’eau",
    "Tapis de sol",
    "Élastique de musculation",
    "Station de gainage",
    "Câble de traction",
    "Corde ondulatoire",
    "Support pour ballons médicinaux",
    "Station de boxe",
    "Chaise romaine",
    "Parallèles",
    "Plateau de plyométrie",
    "Vélo spinning",
    "Tapis de protection",
    "Ventilateur de sport",
    "Sonorisation",
    "Chronomètre",
    "Éclairage LED",
    "Station d’hydratation",
    "Kit de premier secours"
];

// Afficher le tableau dans la console
console.log(salleDeSport);

const chambreEnfant = [
    "Lit enfant",
    "Matelas",
    "Couverture",
    "Oreiller",
    "Couette",
    "Draps",
    "Housses de couette",
    "Alèses",
    "Table à langer",
    "Chaise haute",
    "Armoire",
    "Commode",
    "Jouets",
    "Rideaux",
    "Lampe de nuit",
    "Tapis",
    "Étagères",
    "Mobiliers de rangement",
    "Bureau pour enfant",
    "Chaise de bureau",
    "Mobile",
    "Table de jeux",
    "Mur d’escalade",
    "Panneaux décoratifs",
    "Casiers",
    "Bac de rangement",
    "Trampoline intérieur",
    "Portemanteaux",
    "Kit de peinture pour enfants",
    "Boîte à jouets",
    "Kit de lecture",
    "Table d’activités",
    "Vêtements de lit",
    "Cadres pour photos",
    "Poupées",
    "Coussin de lecture",
    "Luminaires colorés",
    "Rideaux occultants",
    "Horloge murale",
    "Étagères murales",
    "Lit superposé",
    "Fauteuil confortable",
    "Mur d’escalade pour enfants",
    "Écran de projection",
    "Murs magnétiques",
    "Panier de rangement",
    "Table à dessin",
    "Boîte de bricolage",
    "Support pour livres",
    "Éclairage LED amusant"
];

// Afficher le tableau dans la console
console.log(chambreEnfant);

const bibliotheque = [
    "Étagères murales",
    "Bibliothèque modulaire",
    "Fauteuil confortable",
    "Lampadaire",
    "Table de lecture",
    "Meuble de rangement",
    "Bibliothèque à roulettes",
    "Réglage de lumière",
    "Cadres de livres",
    "Poufs",
    "Chaises de lecture",
    "Table basse",
    "Étagères à livres inclinées",
    "Éclairage de lecture",
    "Table d’écriture",
    "Support de livres",
    "Porte-revues",
    "Porte-stylos",
    "Cadres photo",
    "Décorations murales",
    "Horloge murale",
    "Étagères ouvertes",
    "Plantes en pot",
    "Coffre de rangement",
    "Tablette de lecture",
    "Étagères en bois",
    "Meuble à tiroirs",
    "Tapis de lecture",
    "Étagères de coin",
    "Panier de rangement",
    "Éclairage LED",
    "Miroir décoratif",
    "Étagère à vin",
    "Tapis",
    "Rideaux",
    "Mur de briques décoratives",
    "Étagères empilables",
    "Bibliothèque avec escabeau",
    "Vitrine de bibliothèque",
    "Plantes suspendues",
    "Étagères de rangement pour CD/DVD",
    "Banc de bibliothèque",
    "Étagères mobiles",
    "Support pour lecteurs",
    "Table d’appoint",
    "Meuble à livres en verre",
    "Étagères en métal",
    "Porte-étiquettes pour livres",
    "Tableau d’affichage",
    "Paniers de rangement"
];

// Afficher le tableau dans la console
console.log(bibliotheque);

const salleDeMusique = [
    "Piano",
    "Guitare",
    "Batterie",
    "Amplificateur",
    "Micros",
    "Étagères à partitions",
    "Casque audio",
    "Système de sonorisation",
    "Table de mixage",
    "Moniteurs de studio",
    "Câbles audio",
    "Supports pour instruments",
    "Métronome",
    "Accordeurs",
    "Haut-parleurs",
    "Éclairage d’ambiance",
    "Panneaux acoustiques",
    "Enregistreur audio",
    "Studio d’enregistrement",
    "Support de partitions",
    "Clavier MIDI",
    "Enceintes de monitoring",
    "Pieds de microphone",
    "Synthétiseur",
    "Équipement de son",
    "Partition numérique",
    "Ampli de guitare",
    "Table de studio",
    "Réglages acoustiques",
    "Câble d’instrument",
    "Écran de séparation",
    "Support pour casque",
    "Housses de protection",
    "Kit de nettoyage pour instruments",
    "Équipement d’enregistrement",
    "Pieds d’instrument",
    "Banc de musique",
    "Station de travail audio",
    "Éclairage LED de scène",
    "Station de mixage audio",
    "Enregistreur numérique",
    "Supports de câbles",
    "Affichage de partitions",
    "Chaises de studio",
    "Écran acoustique",
    "Boîte à rythmes",
    "Microphone de studio",
    "Système de diffusion",
    "Réverbération",
    "Équipement de montage"
];

// Afficher le tableau dans la console
console.log(salleDeMusique);

const cuisineDeChef = [
    "Cuisinière professionnelle",
    "Four à convection",
    "Réfrigérateur industriel",
    "Congélateur",
    "Lave-vaisselle commercial",
    "Plancha",
    "Hotte aspirante",
    "Mixeur industriel",
    "Robot culinaire",
    "Évier double",
    "Table de travail en inox",
    "Échelle de cuisine",
    "Cuiseur vapeur",
    "Grille-pain professionnel",
    "Batteur sur socle",
    "Machine à café",
    "Ustensiles de cuisine en inox",
    "Poêles et casseroles",
    "Poubelle de tri",
    "Contenants de stockage",
    "Tablier de cuisine",
    "Couteaux de chef",
    "Planche à découper",
    "Presse-agrumes",
    "Sous-vide",
    "Émulsionneur",
    "Thermomètre de cuisine",
    "Râpe à fromage",
    "Éplucheur",
    "Mélangeur à main",
    "Entonnoir",
    "Louche",
    "Spatules",
    "Passoire",
    "Mortier et pilon",
    "Récipients en verre",
    "Poches à douille",
    "Couteaux à pain",
    "Gobelet doseur",
    "Grille-pain à longue fente",
    "Machine à pâtes",
    "Tamis",
    "Plaques de cuisson",
    "Râpe à légumes",
    "Boîtes de conservation",
    "Découpe-pizza",
    "Feuille de cuisson",
    "Louche",
    "Batteur à œufs",
    "Ouvre-boîte"
];

// Afficher le tableau dans la console
console.log(cuisineDeChef);


